<?php

declare(strict_types=1);

namespace App\Models;

use Carbon\CarbonImmutable;
use Database\Factories\CertificateFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * A certificate of completion (design handoff §7, FR-PROG-08).
 *
 * ═════════════════════════════════════════════════════════════════════════
 * THE NAME AND TITLE ON THIS ROW ARE SNAPSHOTS. DO NOT REPLACE THEM WITH JOINS.
 *
 * A certificate states what was awarded to whom on a date. Rendering the
 * learner's current name or the course's current title would mean an edit in
 * 2027 silently rewrites a document an employer verified in 2026, and every
 * already-downloaded copy would disagree with the system of record.
 *
 * The relations below exist for linking and authorisation — never for the text
 * printed on the certificate itself.
 * ═════════════════════════════════════════════════════════════════════════
 *
 * @property int $id
 * @property int $enrollment_id
 * @property int $user_id
 * @property int $course_id
 * @property string $number
 * @property string $recipient_name
 * @property string $course_title
 * @property CarbonImmutable $issued_at
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 */
final class Certificate extends Model
{
    /** @use HasFactory<CertificateFactory> */
    use HasFactory;

    /**
     * `number` is absent deliberately. It is generated by IssueCertificate and
     * must never arrive from input — a caller able to choose it could collide
     * with, or impersonate, an award already made.
     *
     * @var list<string>
     */
    protected $fillable = [
        'enrollment_id',
        'user_id',
        'course_id',
        'recipient_name',
        'course_title',
        'issued_at',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'issued_at' => 'immutable_datetime',
        ];
    }

    /**
     * Looked up by `number` in URLs, never by id.
     *
     * A sequential id in a verification link would let anyone walk the whole
     * set of awards the organisation has ever made.
     */
    public function getRouteKeyName(): string
    {
        return 'number';
    }

    /**
     * @return BelongsTo<Enrollment, $this>
     */
    public function enrollment(): BelongsTo
    {
        return $this->belongsTo(Enrollment::class);
    }

    /**
     * @return BelongsTo<User, $this>
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return BelongsTo<Course, $this>
     */
    public function course(): BelongsTo
    {
        return $this->belongsTo(Course::class);
    }
}
